import { registerUrql } from "@urql/next/rsc";
import type { Metadata } from "next";
import { cacheExchange, createClient, fetchExchange } from "urql";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const makeClient = () => {
  return createClient({
    url: "https://graphqlzero.almansi.me/api",
    exchanges: [cacheExchange, fetchExchange],
  });
};

export const { getClient } = registerUrql(makeClient);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  );
}
